kind: pipeline
name: default

steps:
  - name: pull submodules
    image: docker:git
    commands:
    - git submodule update --depth 5 --init --recursive
- name: formplayer docker build
  image: plugins/docker
  settings:
    repo: kkrampa/formplayer
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
