pipeline:
  publish-docker-image---build-number:
    image: plugins/docker:17.12
    repo: kkrampa/formplayer
    secrets: [ docker_username, docker_password ]
    label_schema:
    - ci-build-number=${DRONE_BUILD_NUMBER}
    - vcs-commit-branch=${DRONE_COMMIT_BRANCH}
    - vcs-commit-sha=${DRONE_COMMIT_SHA}
    tags:
    - ${DRONE_BUILD_NUMBER}
    when:
      event: [ push ]
      branch:
        exclude: [ master ]
