version: 0.2

phases:
  pre_build:
    commands:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD 
  build:
    commands:
      - docker build -t kkrampa/formplayer:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - docker push kkrampa/formplayer:$CODEBUILD_RESOLVED_SOURCE_VERSION
